{
  "openapi": "3.0.1",
  "info": {
    "title": "Tenants API",
    "description": "Tenants backend API documentation",
    "version": "0.1.0"
  },
  "servers": [
    {
      "url": "http://localhost:3000"
    }
  ],
  "paths": {
    "/auth/login": {
      "post": {
        "tags": [
          "Auth"
        ],
        "summary": "Login user",
        "description": "Returns access token",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "example": {
                  "email": "example@example.com",
                  "password": "test123"
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "example": {
                    "user": {
                      "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVjYWNlNzZlOTJlN2FmMjJiYmQ0YjkzYyIsImV4cCI6MTU2MDM1OTM2NywiaWF0IjoxNTU1MTc1MzY3fQ.Rlyx4L4RNqLLJy306jOEZ2yR_PICum3QdSgw1cr2o_4"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/auth/register": {
      "post": {
        "tags": [
          "Auth"
        ],
        "summary": "Register user",
        "description": "Returns access token",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "example": {
                  "username": "example",
                  "email": "example@example.com",
                  "password": "test123",
                  "bank_account_number": "123123123123123123123123123"
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "example": {
                    "user": {
                      "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVjYWNlNzZlOTJlN2FmMjJiYmQ0YjkzYyIsImV4cCI6MTU2MDM1OTM2NywiaWF0IjoxNTU1MTc1MzY3fQ.Rlyx4L4RNqLLJy306jOEZ2yR_PICum3QdSgw1cr2o_4"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/users/groups": {
      "get": {
        "tags": [
          "Users"
        ],
        "summary": "Get user groups",
        "description": "Returns all groups where user belong",
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "example": {
                    "groups": [
                      {
                        "members": [
                          {
                            "_id": "5c91564abb6d7f5780d072ff",
                            "username": "example122",
                            "email": "example@exmple.com",
                            "createdAt": "2019-03-19T20:51:22.481Z",
                            "updatedAt": "2019-03-19T20:51:22.481Z"
                          }
                        ],
                        "_id": "5cb0ccfcbbdabd3ea2600d72",
                        "name": "Nowa grupa",
                        "owner": {
                          "_id": "5c91564abb6d7f5780d072ff",
                          "username": "example122",
                          "email": "example@exmple.com",
                          "createdAt": "2019-03-19T20:51:22.481Z",
                          "updatedAt": "2019-03-19T20:51:22.481Z"
                        },
                        "createdAt": "2019-04-12T17:38:04.747Z",
                        "updatedAt": "2019-04-12T17:38:04.747Z"
                      },
                      {
                        "members": [
                          {
                            "_id": "5c91564abb6d7f5780d072ff",
                            "username": "example122",
                            "email": "example@exmple.com",
                            "createdAt": "2019-03-19T20:51:22.481Z",
                            "updatedAt": "2019-03-19T20:51:22.481Z"
                          }
                        ],
                        "_id": "5cb0d2ad4c0ee5406365be2b",
                        "name": "Druga grupa",
                        "owner": {
                          "_id": "5c91564abb6d7f5780d072ff",
                          "username": "example122",
                          "email": "example@exmple.com",
                          "createdAt": "2019-03-19T20:51:22.481Z",
                          "updatedAt": "2019-03-19T20:51:22.481Z"
                        },
                        "createdAt": "2019-04-12T18:02:21.240Z",
                        "updatedAt": "2019-04-12T20:06:10.170Z"
                      }
                    ]
                  }
                }
              }
            }
          }
        }
      }
    },
    "/groups/new": {
      "post": {
        "tags": [
          "Group"
        ],
        "summary": "Add new group",
        "description": "Returns all groups where user belong",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "example": {
                  "name": "Example Group"
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "example": {
                    "group": {
                      "members": [
                        "5c91564abb6d7f5780d072ff"
                      ],
                      "_id": "5cb22da165f312860a7f4472",
                      "name": "exampleeGroup",
                      "owner": "5c91564abb6d7f5780d072ff",
                      "createdAt": "2019-04-13T18:42:41.535Z",
                      "updatedAt": "2019-04-13T18:42:41.535Z"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/groups/generate_member_link": {
      "post": {
        "tags": [
          "Group"
        ],
        "summary": "Generate member invitation link",
        "description": "Returns link to activate member in group",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "example": {
                  "email": "example@example.com",
                  "group_id": "5cb22da165f312860a7f4472"
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "example": {
                    "link": "http://localhost:3000/groups/activate_member/fee7005951a3c52419bf170c97e851299ddb8ba5b30a35c03467de3b7c5ce6b5eb09442702d10739c02d4832da0dfed439058496de2843ad2a4d47c07694e69d"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/groups/{groupId}/members": {
      "get": {
        "tags": [
          "Group"
        ],
        "summary": "Get members of group",
        "description": "Returns members of group",
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "example": {
                    "members": [
                      {
                        "_id": "5cdb048df901520606166a59",
                        "username": "test testowski",
                        "email": "test@example.com",
                        "bank_account_number": "2137",
                        "createdAt": "2019-05-14T18:10:22.313Z",
                        "updatedAt": "2019-05-14T18:10:22.313Z",
                        "__v": 0
                      },
                      {
                        "_id": "5ccaff4d664c582c6b8d6e29",
                        "username": "janusz",
                        "email": "janusz@example.com",
                        "bank_account_number": "2137",
                        "createdAt": "2019-05-02T14:31:42.124Z",
                        "updatedAt": "2019-05-02T14:31:42.124Z",
                        "__v": 0
                      }
                    ]
                  }
                }
              }
            }
          }
        }
      }
    },
    "/groups/{groupId}/members/{userId}": {
      "get": {
        "tags": [
          "Group"
        ],
        "summary": "Get single member of group",
        "description": "Returns single member of group",
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "example": {
                    "member": {
                      "_id": "5cdb048df901520606166a59",
                      "username": "test testowski",
                      "email": "test@example.com",
                      "bank_account_number": "2137",
                      "createdAt": "2019-05-14T18:10:22.313Z",
                      "updatedAt": "2019-05-14T18:10:22.313Z",
                      "__v": 0
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/groups/{groupId}/bills": {
      "get": {
        "tags": [
          "Bills"
        ],
        "summary": "Get bills in group",
        "description": "Returns bills of group",
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "example": {
                    "bills": [
                      {
                        "debtors": [
                          {
                            "paid": false,
                            "_id": "5cf41cd921eacd40e4bdfd11",
                            "user": "5cdb048df901520606166a59",
                            "value": 10.69,
                            "__v": 0
                          }
                        ],
                        "_id": "5cf41cd921eacd40e4bdfd10",
                        "name": "Rachunki 1",
                        "value": 21.37,
                        "user": {
                          "_id": "5cdb048df901520606166a59",
                          "username": "test testowski",
                          "email": "test@example.com",
                          "bank_account_number": "2137",
                          "createdAt": "2019-05-14T18:10:22.313Z",
                          "updatedAt": "2019-05-14T18:10:22.313Z",
                          "__v": 0
                        },
                        "createdAt": "2019-06-02T19:00:41.853Z",
                        "updatedAt": "2019-06-02T19:00:41.853Z",
                        "__v": 0
                      },
                      {
                        "debtors": [
                          {
                            "paid": false,
                            "_id": "5cf41df846d29f077898b4f0",
                            "user": "5cdb048df901520606166a59",
                            "value": 10.69,
                            "__v": 0
                          }
                        ],
                        "_id": "5cf41df746d29f077898b4ef",
                        "name": "Rachunki 1",
                        "value": 21.37,
                        "user": {
                          "_id": "5cdb048df901520606166a59",
                          "username": "test testowski",
                          "email": "test@example.com",
                          "bank_account_number": "2137",
                          "createdAt": "2019-05-14T18:10:22.313Z",
                          "updatedAt": "2019-05-14T18:10:22.313Z",
                          "__v": 0
                        },
                        "createdAt": "2019-06-02T19:05:28.071Z",
                        "updatedAt": "2019-06-02T19:05:28.071Z",
                        "__v": 0
                      },
                      {
                        "debtors": [
                          {
                            "paid": false,
                            "_id": "5cf41df946d29f077898b4f3",
                            "user": "5cdb048df901520606166a59",
                            "value": 10.69,
                            "__v": 0
                          }
                        ],
                        "_id": "5cf41df946d29f077898b4f2",
                        "name": "Rachunki 1",
                        "value": 21.37,
                        "user": {
                          "_id": "5cdb048df901520606166a59",
                          "username": "test testowski",
                          "email": "test@example.com",
                          "bank_account_number": "2137",
                          "createdAt": "2019-05-14T18:10:22.313Z",
                          "updatedAt": "2019-05-14T18:10:22.313Z",
                          "__v": 0
                        },
                        "createdAt": "2019-06-02T19:05:29.750Z",
                        "updatedAt": "2019-06-02T19:05:29.750Z",
                        "__v": 0
                      },
                      {
                        "debtors": [
                          {
                            "paid": false,
                            "_id": "5cf41dfa46d29f077898b4f6",
                            "user": "5cdb048df901520606166a59",
                            "value": 10.69,
                            "__v": 0
                          }
                        ],
                        "_id": "5cf41dfa46d29f077898b4f5",
                        "name": "Rachunki 1",
                        "value": 21.37,
                        "user": {
                          "_id": "5cdb048df901520606166a59",
                          "username": "test testowski",
                          "email": "test@example.com",
                          "bank_account_number": "2137",
                          "createdAt": "2019-05-14T18:10:22.313Z",
                          "updatedAt": "2019-05-14T18:10:22.313Z",
                          "__v": 0
                        },
                        "createdAt": "2019-06-02T19:05:30.517Z",
                        "updatedAt": "2019-06-02T19:05:30.517Z",
                        "__v": 0
                      },
                      {
                        "debtors": [
                          {
                            "paid": false,
                            "_id": "5cf41dfb46d29f077898b4f9",
                            "user": "5cdb048df901520606166a59",
                            "value": 10.69,
                            "__v": 0
                          }
                        ],
                        "_id": "5cf41dfb46d29f077898b4f8",
                        "name": "Rachunki 1",
                        "value": 21.37,
                        "user": {
                          "_id": "5cdb048df901520606166a59",
                          "username": "test testowski",
                          "email": "test@example.com",
                          "bank_account_number": "2137",
                          "createdAt": "2019-05-14T18:10:22.313Z",
                          "updatedAt": "2019-05-14T18:10:22.313Z",
                          "__v": 0
                        },
                        "createdAt": "2019-06-02T19:05:31.216Z",
                        "updatedAt": "2019-06-02T19:05:31.216Z",
                        "__v": 0
                      },
                      {
                        "debtors": [
                          {
                            "paid": false,
                            "_id": "5cf42911f23a432f88465e94",
                            "user": "5cdb048df901520606166a59",
                            "value": 10.69,
                            "__v": 0
                          }
                        ],
                        "_id": "5cf42910f23a432f88465e93",
                        "name": "Rachunki 1",
                        "value": 21.37,
                        "user": {
                          "_id": "5cdb048df901520606166a59",
                          "username": "test testowski",
                          "email": "test@example.com",
                          "bank_account_number": "2137",
                          "createdAt": "2019-05-14T18:10:22.313Z",
                          "updatedAt": "2019-05-14T18:10:22.313Z",
                          "__v": 0
                        },
                        "createdAt": "2019-06-02T19:52:49.490Z",
                        "updatedAt": "2019-06-02T19:52:49.490Z",
                        "__v": 0
                      },
                      {
                        "debtors": [
                          {
                            "paid": false,
                            "_id": "5cf42fe55e52cd4910a4f62e",
                            "user": "5cdb048df901520606166a59",
                            "value": 105,
                            "__v": 0
                          }
                        ],
                        "_id": "5cf42fe45e52cd4910a4f62d",
                        "name": "Cośtam",
                        "value": 210,
                        "user": {
                          "_id": "5cdb048df901520606166a59",
                          "username": "test testowski",
                          "email": "test@example.com",
                          "bank_account_number": "2137",
                          "createdAt": "2019-05-14T18:10:22.313Z",
                          "updatedAt": "2019-05-14T18:10:22.313Z",
                          "__v": 0
                        },
                        "createdAt": "2019-06-02T20:21:57.300Z",
                        "updatedAt": "2019-06-02T20:21:57.300Z",
                        "__v": 0
                      },
                      {
                        "debtors": [
                          {
                            "paid": false,
                            "_id": "5cf4312c8b1c3c4a5052a276",
                            "user": "5cdb048df901520606166a59",
                            "value": 105,
                            "__v": 0
                          }
                        ],
                        "_id": "5cf4312b8b1c3c4a5052a275",
                        "name": "Cośtam",
                        "value": 210,
                        "user": {
                          "_id": "5cdb048df901520606166a59",
                          "username": "test testowski",
                          "email": "test@example.com",
                          "bank_account_number": "2137",
                          "createdAt": "2019-05-14T18:10:22.313Z",
                          "updatedAt": "2019-05-14T18:10:22.313Z",
                          "__v": 0
                        },
                        "createdAt": "2019-06-02T20:27:24.343Z",
                        "updatedAt": "2019-06-02T20:27:24.343Z",
                        "__v": 0
                      },
                      {
                        "debtors": [
                          {
                            "paid": false,
                            "_id": "5cf431b235e2ab2cf0b35417",
                            "user": "5cdb048df901520606166a59",
                            "value": 105,
                            "__v": 0
                          }
                        ],
                        "_id": "5cf431b135e2ab2cf0b35416",
                        "name": "Cośtam",
                        "value": 210,
                        "user": {
                          "_id": "5cdb048df901520606166a59",
                          "username": "test testowski",
                          "email": "test@example.com",
                          "bank_account_number": "2137",
                          "createdAt": "2019-05-14T18:10:22.313Z",
                          "updatedAt": "2019-05-14T18:10:22.313Z",
                          "__v": 0
                        },
                        "createdAt": "2019-06-02T20:29:38.322Z",
                        "updatedAt": "2019-06-02T20:29:38.322Z",
                        "__v": 0
                      },
                      {
                        "debtors": [
                          {
                            "paid": false,
                            "_id": "5cf4339f35e2ab2cf0b3541a",
                            "user": "5cdb048df901520606166a59",
                            "value": 1000,
                            "__v": 0
                          }
                        ],
                        "_id": "5cf4339f35e2ab2cf0b35419",
                        "name": "Rachunki za maj",
                        "value": 2000,
                        "user": {
                          "_id": "5cdb048df901520606166a59",
                          "username": "test testowski",
                          "email": "test@example.com",
                          "bank_account_number": "2137",
                          "createdAt": "2019-05-14T18:10:22.313Z",
                          "updatedAt": "2019-05-14T18:10:22.313Z",
                          "__v": 0
                        },
                        "createdAt": "2019-06-02T20:37:51.990Z",
                        "updatedAt": "2019-06-02T20:37:51.990Z",
                        "__v": 0
                      }
                    ]
                  }
                }
              }
            }
          }
        }
      }
    },
    "/groups/{groupId}/bills": {
      "post": {
        "tags": [
          "Bills"
        ],
        "summary": "Create new bill",
        "description": "Create new bill",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "example": {
                  "name": "Rachunki",
                  "value": 33
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "example": {
                    "bill": {
                      "debtors": [
                        "5cf436bcd9aec4139c179b25",
                        "5cf436bcd9aec4139c179b26"
                      ],
                      "_id": "5cf436bcd9aec4139c179b24",
                      "name": "Rachunki",
                      "value": 33,
                      "user": "5cdb048df901520606166a59",
                      "createdAt": "2019-06-02T20:51:08.478Z",
                      "updatedAt": "2019-06-02T20:51:08.478Z",
                      "__v": 0
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/groups/{groupId}/bills/{billId}/paid": {
      "post": {
        "tags": [
          "Bills"
        ],
        "summary": "Sets bill as paid",
        "description": "Sets bill as paid",
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "example": {
                    "debtor": {
                      "paid": true,
                      "_id": "5cf436bcd9aec4139c179b25",
                      "user": "5cdb048df901520606166a59",
                      "value": 16.5,
                      "__v": 0
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/groups/{groupId}/bills/{billId}": {
      "get": {
        "tags": [
          "Bills"
        ],
        "summary": "Get single bill",
        "description": "Get single bill",
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "example": {
                    "bill": {
                      "debtors": [
                        {
                          "paid": false,
                          "_id": "5cf436bcd9aec4139c179b25",
                          "user": {
                            "_id": "5cdb048df901520606166a59",
                            "username": "test testowski",
                            "email": "test@example.com",
                            "bank_account_number": "2137",
                            "createdAt": "2019-05-14T18:10:22.313Z",
                            "updatedAt": "2019-05-14T18:10:22.313Z",
                            "__v": 0
                          },
                          "value": 16.5,
                          "__v": 0
                        },
                        {
                          "paid": false,
                          "_id": "5cf436bcd9aec4139c179b26",
                          "user": {
                            "_id": "5ccaff4d664c582c6b8d6e29",
                            "username": "janusz",
                            "email": "janusz@example.com",
                            "bank_account_number": "2137",
                            "createdAt": "2019-05-02T14:31:42.124Z",
                            "updatedAt": "2019-05-02T14:31:42.124Z",
                            "__v": 0
                          },
                          "value": 16.5,
                          "__v": 0
                        }
                      ],
                      "_id": "5cf436bcd9aec4139c179b24",
                      "name": "Rachunki",
                      "value": 33,
                      "user": {
                        "_id": "5cdb048df901520606166a59",
                        "username": "test testowski",
                        "email": "test@example.com",
                        "bank_account_number": "2137",
                        "createdAt": "2019-05-14T18:10:22.313Z",
                        "updatedAt": "2019-05-14T18:10:22.313Z",
                        "__v": 0
                      },
                      "createdAt": "2019-06-02T20:51:08.478Z",
                      "updatedAt": "2019-06-02T20:51:08.478Z",
                      "__v": 0
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/groups/{groupId}/debts ": {
      "get": {
        "tags": [
          "Debts"
        ],
        "summary": "Get my debts",
        "description": "Get my debts",
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "example": {
                    "debts": [
                      {
                        "paid": false,
                        "_id": "5cf6e0fa4978db3d44d67458",
                        "name": "Rachunki",
                        "holder": {
                          "_id": "5cdb048df901520606166a59",
                          "username": "test testowski",
                          "email": "test@example.com",
                          "bank_account_number": "2137",
                          "createdAt": "2019-05-14T18:10:22.313Z",
                          "updatedAt": "2019-05-14T18:10:22.313Z",
                          "__v": 0
                        },
                        "debtor": {
                          "_id": "5cdb048df901520606166a59",
                          "username": "test testowski",
                          "email": "test@example.com",
                          "bank_account_number": "2137",
                          "createdAt": "2019-05-14T18:10:22.313Z",
                          "updatedAt": "2019-05-14T18:10:22.313Z",
                          "__v": 0
                        },
                        "value": 33,
                        "createdAt": "2019-06-04T21:22:02.821Z",
                        "updatedAt": "2019-06-04T21:22:02.821Z",
                        "__v": 0
                      },
                      {
                        "paid": false,
                        "_id": "5cf6da8784b70130589844eb",
                        "name": "Rachunki",
                        "holder": {
                          "_id": "5cdb048df901520606166a59",
                          "username": "test testowski",
                          "email": "test@example.com",
                          "bank_account_number": "2137",
                          "createdAt": "2019-05-14T18:10:22.313Z",
                          "updatedAt": "2019-05-14T18:10:22.313Z",
                          "__v": 0
                        },
                        "debtor": {
                          "_id": "5cdb048df901520606166a59",
                          "username": "test testowski",
                          "email": "test@example.com",
                          "bank_account_number": "2137",
                          "createdAt": "2019-05-14T18:10:22.313Z",
                          "updatedAt": "2019-05-14T18:10:22.313Z",
                          "__v": 0
                        },
                        "value": 33,
                        "createdAt": "2019-06-04T20:54:31.672Z",
                        "updatedAt": "2019-06-04T21:21:57.543Z",
                        "__v": 0
                      },
                      {
                        "paid": false,
                        "_id": "5cf6d808082ca84a20fb1f5f",
                        "name": "Rachunki",
                        "holder": {
                          "_id": "5cdb048df901520606166a59",
                          "username": "test testowski",
                          "email": "test@example.com",
                          "bank_account_number": "2137",
                          "createdAt": "2019-05-14T18:10:22.313Z",
                          "updatedAt": "2019-05-14T18:10:22.313Z",
                          "__v": 0
                        },
                        "debtor": {
                          "_id": "5cdb048df901520606166a59",
                          "username": "test testowski",
                          "email": "test@example.com",
                          "bank_account_number": "2137",
                          "createdAt": "2019-05-14T18:10:22.313Z",
                          "updatedAt": "2019-05-14T18:10:22.313Z",
                          "__v": 0
                        },
                        "value": 33,
                        "createdAt": "2019-06-04T20:43:52.740Z",
                        "updatedAt": "2019-06-04T20:43:52.740Z",
                        "__v": 0
                      },
                      {
                        "paid": false,
                        "_id": "5cf6d808082ca84a20fb1f5e",
                        "name": "Rachunki",
                        "holder": {
                          "_id": "5cdb048df901520606166a59",
                          "username": "test testowski",
                          "email": "test@example.com",
                          "bank_account_number": "2137",
                          "createdAt": "2019-05-14T18:10:22.313Z",
                          "updatedAt": "2019-05-14T18:10:22.313Z",
                          "__v": 0
                        },
                        "debtor": {
                          "_id": "5cdb048df901520606166a59",
                          "username": "test testowski",
                          "email": "test@example.com",
                          "bank_account_number": "2137",
                          "createdAt": "2019-05-14T18:10:22.313Z",
                          "updatedAt": "2019-05-14T18:10:22.313Z",
                          "__v": 0
                        },
                        "value": 33,
                        "createdAt": "2019-06-04T20:43:52.294Z",
                        "updatedAt": "2019-06-04T21:01:52.983Z",
                        "__v": 0
                      },
                      {
                        "paid": true,
                        "_id": "5cf6d807082ca84a20fb1f5d",
                        "name": "Rachunki",
                        "holder": {
                          "_id": "5cdb048df901520606166a59",
                          "username": "test testowski",
                          "email": "test@example.com",
                          "bank_account_number": "2137",
                          "createdAt": "2019-05-14T18:10:22.313Z",
                          "updatedAt": "2019-05-14T18:10:22.313Z",
                          "__v": 0
                        },
                        "debtor": {
                          "_id": "5cdb048df901520606166a59",
                          "username": "test testowski",
                          "email": "test@example.com",
                          "bank_account_number": "2137",
                          "createdAt": "2019-05-14T18:10:22.313Z",
                          "updatedAt": "2019-05-14T18:10:22.313Z",
                          "__v": 0
                        },
                        "value": 33,
                        "createdAt": "2019-06-04T20:43:51.685Z",
                        "updatedAt": "2019-06-04T20:59:46.822Z",
                        "__v": 0
                      },
                      {
                        "paid": false,
                        "_id": "5cf6d807082ca84a20fb1f5c",
                        "name": "Rachunki",
                        "holder": {
                          "_id": "5cdb048df901520606166a59",
                          "username": "test testowski",
                          "email": "test@example.com",
                          "bank_account_number": "2137",
                          "createdAt": "2019-05-14T18:10:22.313Z",
                          "updatedAt": "2019-05-14T18:10:22.313Z",
                          "__v": 0
                        },
                        "debtor": {
                          "_id": "5cdb048df901520606166a59",
                          "username": "test testowski",
                          "email": "test@example.com",
                          "bank_account_number": "2137",
                          "createdAt": "2019-05-14T18:10:22.313Z",
                          "updatedAt": "2019-05-14T18:10:22.313Z",
                          "__v": 0
                        },
                        "value": 33,
                        "createdAt": "2019-06-04T20:43:51.238Z",
                        "updatedAt": "2019-06-04T20:43:51.238Z",
                        "__v": 0
                      },
                      {
                        "paid": false,
                        "_id": "5cf6d806082ca84a20fb1f5b",
                        "name": "Rachunki",
                        "holder": {
                          "_id": "5cdb048df901520606166a59",
                          "username": "test testowski",
                          "email": "test@example.com",
                          "bank_account_number": "2137",
                          "createdAt": "2019-05-14T18:10:22.313Z",
                          "updatedAt": "2019-05-14T18:10:22.313Z",
                          "__v": 0
                        },
                        "debtor": {
                          "_id": "5cdb048df901520606166a59",
                          "username": "test testowski",
                          "email": "test@example.com",
                          "bank_account_number": "2137",
                          "createdAt": "2019-05-14T18:10:22.313Z",
                          "updatedAt": "2019-05-14T18:10:22.313Z",
                          "__v": 0
                        },
                        "value": 33,
                        "createdAt": "2019-06-04T20:43:50.576Z",
                        "updatedAt": "2019-06-04T20:43:50.576Z",
                        "__v": 0
                      },
                      {
                        "paid": false,
                        "_id": "5cf6d805082ca84a20fb1f5a",
                        "name": "Rachunki",
                        "holder": {
                          "_id": "5cdb048df901520606166a59",
                          "username": "test testowski",
                          "email": "test@example.com",
                          "bank_account_number": "2137",
                          "createdAt": "2019-05-14T18:10:22.313Z",
                          "updatedAt": "2019-05-14T18:10:22.313Z",
                          "__v": 0
                        },
                        "debtor": {
                          "_id": "5cdb048df901520606166a59",
                          "username": "test testowski",
                          "email": "test@example.com",
                          "bank_account_number": "2137",
                          "createdAt": "2019-05-14T18:10:22.313Z",
                          "updatedAt": "2019-05-14T18:10:22.313Z",
                          "__v": 0
                        },
                        "value": 33,
                        "createdAt": "2019-06-04T20:43:49.581Z",
                        "updatedAt": "2019-06-04T20:43:49.581Z",
                        "__v": 0
                      }
                    ]
                  }
                }
              }
            }
          }
        }
      }
    },
    "/groups/{groupId}/debts": {
      "post": {
        "tags": [
          "Debts"
        ],
        "summary": "Create new debt / give a loan",
        "description": "Create new debt / give a loan",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "example": {
                  "name": "Pożyczka",
                  "value": 33,
                  "debtor": ":debtor_id"
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "example": {
                    "debt": {
                      "paid": false,
                      "_id": "5cf6e52c39de05512077dfbc",
                      "name": "testing",
                      "holder": "5cdb048df901520606166a59",
                      "debtor": "5cdb048df901520606166a59",
                      "value": 33,
                      "createdAt": "2019-06-04T21:39:56.475Z",
                      "updatedAt": "2019-06-04T21:39:56.475Z",
                      "__v": 0
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/groups/{groupId}/debts/given": {
      "get": {
        "tags": [
          "Debts"
        ],
        "summary": "Get given loans",
        "description": "Get given loans",
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "example": {
                    "debts": [
                      {
                        "paid": false,
                        "_id": "5cf6e0fa4978db3d44d67458",
                        "name": "Rachunki",
                        "holder": {
                          "_id": "5cdb048df901520606166a59",
                          "username": "test testowski",
                          "email": "test@example.com",
                          "bank_account_number": "2137",
                          "createdAt": "2019-05-14T18:10:22.313Z",
                          "updatedAt": "2019-05-14T18:10:22.313Z",
                          "__v": 0
                        },
                        "debtor": {
                          "_id": "5cdb048df901520606166a59",
                          "username": "test testowski",
                          "email": "test@example.com",
                          "bank_account_number": "2137",
                          "createdAt": "2019-05-14T18:10:22.313Z",
                          "updatedAt": "2019-05-14T18:10:22.313Z",
                          "__v": 0
                        },
                        "value": 33,
                        "createdAt": "2019-06-04T21:22:02.821Z",
                        "updatedAt": "2019-06-04T21:22:02.821Z",
                        "__v": 0
                      },
                      {
                        "paid": false,
                        "_id": "5cf6da8784b70130589844eb",
                        "name": "Rachunki",
                        "holder": {
                          "_id": "5cdb048df901520606166a59",
                          "username": "test testowski",
                          "email": "test@example.com",
                          "bank_account_number": "2137",
                          "createdAt": "2019-05-14T18:10:22.313Z",
                          "updatedAt": "2019-05-14T18:10:22.313Z",
                          "__v": 0
                        },
                        "debtor": {
                          "_id": "5cdb048df901520606166a59",
                          "username": "test testowski",
                          "email": "test@example.com",
                          "bank_account_number": "2137",
                          "createdAt": "2019-05-14T18:10:22.313Z",
                          "updatedAt": "2019-05-14T18:10:22.313Z",
                          "__v": 0
                        },
                        "value": 33,
                        "createdAt": "2019-06-04T20:54:31.672Z",
                        "updatedAt": "2019-06-04T21:21:57.543Z",
                        "__v": 0
                      },
                      {
                        "paid": false,
                        "_id": "5cf6d808082ca84a20fb1f5f",
                        "name": "Rachunki",
                        "holder": {
                          "_id": "5cdb048df901520606166a59",
                          "username": "test testowski",
                          "email": "test@example.com",
                          "bank_account_number": "2137",
                          "createdAt": "2019-05-14T18:10:22.313Z",
                          "updatedAt": "2019-05-14T18:10:22.313Z",
                          "__v": 0
                        },
                        "debtor": {
                          "_id": "5cdb048df901520606166a59",
                          "username": "test testowski",
                          "email": "test@example.com",
                          "bank_account_number": "2137",
                          "createdAt": "2019-05-14T18:10:22.313Z",
                          "updatedAt": "2019-05-14T18:10:22.313Z",
                          "__v": 0
                        },
                        "value": 33,
                        "createdAt": "2019-06-04T20:43:52.740Z",
                        "updatedAt": "2019-06-04T20:43:52.740Z",
                        "__v": 0
                      },
                      {
                        "paid": false,
                        "_id": "5cf6d808082ca84a20fb1f5e",
                        "name": "Rachunki",
                        "holder": {
                          "_id": "5cdb048df901520606166a59",
                          "username": "test testowski",
                          "email": "test@example.com",
                          "bank_account_number": "2137",
                          "createdAt": "2019-05-14T18:10:22.313Z",
                          "updatedAt": "2019-05-14T18:10:22.313Z",
                          "__v": 0
                        },
                        "debtor": {
                          "_id": "5cdb048df901520606166a59",
                          "username": "test testowski",
                          "email": "test@example.com",
                          "bank_account_number": "2137",
                          "createdAt": "2019-05-14T18:10:22.313Z",
                          "updatedAt": "2019-05-14T18:10:22.313Z",
                          "__v": 0
                        },
                        "value": 33,
                        "createdAt": "2019-06-04T20:43:52.294Z",
                        "updatedAt": "2019-06-04T21:01:52.983Z",
                        "__v": 0
                      },
                      {
                        "paid": true,
                        "_id": "5cf6d807082ca84a20fb1f5d",
                        "name": "Rachunki",
                        "holder": {
                          "_id": "5cdb048df901520606166a59",
                          "username": "test testowski",
                          "email": "test@example.com",
                          "bank_account_number": "2137",
                          "createdAt": "2019-05-14T18:10:22.313Z",
                          "updatedAt": "2019-05-14T18:10:22.313Z",
                          "__v": 0
                        },
                        "debtor": {
                          "_id": "5cdb048df901520606166a59",
                          "username": "test testowski",
                          "email": "test@example.com",
                          "bank_account_number": "2137",
                          "createdAt": "2019-05-14T18:10:22.313Z",
                          "updatedAt": "2019-05-14T18:10:22.313Z",
                          "__v": 0
                        },
                        "value": 33,
                        "createdAt": "2019-06-04T20:43:51.685Z",
                        "updatedAt": "2019-06-04T20:59:46.822Z",
                        "__v": 0
                      },
                      {
                        "paid": false,
                        "_id": "5cf6d807082ca84a20fb1f5c",
                        "name": "Rachunki",
                        "holder": {
                          "_id": "5cdb048df901520606166a59",
                          "username": "test testowski",
                          "email": "test@example.com",
                          "bank_account_number": "2137",
                          "createdAt": "2019-05-14T18:10:22.313Z",
                          "updatedAt": "2019-05-14T18:10:22.313Z",
                          "__v": 0
                        },
                        "debtor": {
                          "_id": "5cdb048df901520606166a59",
                          "username": "test testowski",
                          "email": "test@example.com",
                          "bank_account_number": "2137",
                          "createdAt": "2019-05-14T18:10:22.313Z",
                          "updatedAt": "2019-05-14T18:10:22.313Z",
                          "__v": 0
                        },
                        "value": 33,
                        "createdAt": "2019-06-04T20:43:51.238Z",
                        "updatedAt": "2019-06-04T20:43:51.238Z",
                        "__v": 0
                      },
                      {
                        "paid": false,
                        "_id": "5cf6d806082ca84a20fb1f5b",
                        "name": "Rachunki",
                        "holder": {
                          "_id": "5cdb048df901520606166a59",
                          "username": "test testowski",
                          "email": "test@example.com",
                          "bank_account_number": "2137",
                          "createdAt": "2019-05-14T18:10:22.313Z",
                          "updatedAt": "2019-05-14T18:10:22.313Z",
                          "__v": 0
                        },
                        "debtor": {
                          "_id": "5cdb048df901520606166a59",
                          "username": "test testowski",
                          "email": "test@example.com",
                          "bank_account_number": "2137",
                          "createdAt": "2019-05-14T18:10:22.313Z",
                          "updatedAt": "2019-05-14T18:10:22.313Z",
                          "__v": 0
                        },
                        "value": 33,
                        "createdAt": "2019-06-04T20:43:50.576Z",
                        "updatedAt": "2019-06-04T20:43:50.576Z",
                        "__v": 0
                      },
                      {
                        "paid": false,
                        "_id": "5cf6d805082ca84a20fb1f5a",
                        "name": "Rachunki",
                        "holder": {
                          "_id": "5cdb048df901520606166a59",
                          "username": "test testowski",
                          "email": "test@example.com",
                          "bank_account_number": "2137",
                          "createdAt": "2019-05-14T18:10:22.313Z",
                          "updatedAt": "2019-05-14T18:10:22.313Z",
                          "__v": 0
                        },
                        "debtor": {
                          "_id": "5cdb048df901520606166a59",
                          "username": "test testowski",
                          "email": "test@example.com",
                          "bank_account_number": "2137",
                          "createdAt": "2019-05-14T18:10:22.313Z",
                          "updatedAt": "2019-05-14T18:10:22.313Z",
                          "__v": 0
                        },
                        "value": 33,
                        "createdAt": "2019-06-04T20:43:49.581Z",
                        "updatedAt": "2019-06-04T20:43:49.581Z",
                        "__v": 0
                      }
                    ]
                  }
                }
              }
            }
          }
        }
      }
    },
    "/groups/{groupId}/debts/{debtId}/paid": {
      "post": {
        "tags": [
          "Debts"
        ],
        "summary": "Sets debt as paid",
        "description": "Sets debt as paid",
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "example": {
                    "debt": {
                      "paid": false,
                      "_id": "5cf6e4a547bde53334422ce9",
                      "name": "Rachunek",
                      "holder": "5cdb048df901520606166a59",
                      "debtor": "5cdb048df901520606166a59",
                      "value": 33,
                      "createdAt": "2019-06-04T21:37:41.152Z",
                      "updatedAt": "2019-06-04T21:37:41.152Z",
                      "__v": 0
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "securitySchemes": {
      "bearerAuth": {
        "type": "http",
        "scheme": "bearer",
        "bearerFormat": "JWT"
      }
    }
  },
  "security": {
    "bearerAuth": []
  }
}